server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${storage.db.host}:3306/storage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${storage.db.pw}
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

storage:
  jwt:
    location: classpath:storage.jks
    alias: storage
    password: 2003219
    tokenTTL: 30m
  db:
    host: localhost
    pw: 2003219
