server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${storage.db.host}:3306/storage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${storage.db.pw}
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.shenqy.userservice

knife4j:
  enable: true
  openapi:
    title: 仓储管理系统用户服务接口文档
    description: "仓储管理系统用户服务接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - org.shenqy.userservice.controller
storage:
  jwt:
    location: classpath:storage.jks
    alias: storage
    password: 2003219
    tokenTTL: 30m
  db:
    host: localhost
    pw: 2003219
