server:
  port: 8080
spring:
  application:
    name: storage-gateway
  datasource:
    url: jdbc:mysql://${storage.db.host}:3306/storage_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${storage.db.pw}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/**

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    enable-sql-runner: true
    db-config:
      update-strategy: not_null
      id-type: auto

storage:
  jwt:
    location: classpath:storage.jks
    alias: storage
    password: 2003219
    tokenTTL: 30m
  db:
    host: localhost
    pw: 2003219
  auth:
    excludePaths:
      - /user/login
      - /user/register