server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: storage-gateway
  datasource:
    url: jdbc:mysql://${storage.db.host}:3306/storage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${storage.db.pw}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: users # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/users/**
          filters:
            - StripPrefix=1

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    enable-sql-runner: true
    db-config:
      update-strategy: not_null
      id-type: auto

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true



storage:
  jwt:
    location: classpath:storage.jks
    alias: storage
    password: 2003219
    tokenTTL: 30m
  db:
    host: localhost
    pw: 2003219
  auth:
    excludePaths:
      - /users/user/login
      - /users/user/register
      - /users/v3/api-docs
      - /users/doc.html